version: '3.3'

services:
  front:
    mem_limit: 8G
    build: .
#      context: https://github.com/PeIIIaJIkuH/yerma.git#main
    restart: always
    tty: true
#    command: http-server dist -a 0.0.0.0 -p 8080
    command: yarn run preview --host 0.0.0.0
    ports:
      - "4173:4173"
    env_file:
      - .env
