version: '3'

services:
  front:
    build: .
#      context: https://github.com/PeIIIaJIkuH/yerma.git#main
    restart: always
    tty: true
#    command: http-server dist -a 0.0.0.0 -p 8080
    command: yarn run preview --host 0.0.0.0
    ports:
      - "8080:4173"
    env_file:
      - .env
